### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by rtreharne** [rtreharne/canvasadmin#1]
- [x] Submission Date Range Filter
- [ ] Submission count for students? Do they straddle?
- [ ] capture anonymous id for submission
- [ ] Apply zero scores if later than 5 days
- [ ] ELP extension flag on submission record (SSIS) - override
- [x] Assignment - has overrides?
- [ ] incorporate comments into integrity reporting
- [ ] Assignment: is auto grading on?
- [x] Modules app for exam release - change data action
- [x] Marking Data by module
- [ ] SSIS/Late penalty system

**Comment by rtreharne** [comment]
Completed marking data by module
